remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lips UI Framework
description: Fast, runtime, reactive, lightweight and fully featured UI framework